# pyproject.toml for PLAXIS 3D Spudcan Automation Tool

[tool.black]
# Configuration for the Black code formatter
# See https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-pyproject-toml
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311'] # Specify compatible Python versions

# Optional: include/exclude files or directories
# include = '\.pyi?$'
# exclude = '''
# /(
#    \.eggs
#  | \.git
#  | \.hg
#  | \.mypy_cache
#  | \.tox
#  | \.venv
#  | _build
#  | buck-out
#  | build
#  | dist
# )/
# '''

[tool.isort]
# Configuration for isort (import sorter), often used with Black
profile = "black"
line_length = 88
multi_line_output = 3 # Vertical Hanging Indent
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = ["*/setup.py"] # Example: skip setup.py if it has specific import order needs

# You can add other tool configurations here, e.g., for pytest, mypy, etc.
# [tool.pytest.ini_options]
# minversion = "6.0"
# addopts = "-ra -q"
# testpaths = [
#     "tests",
# ]
